language: python
sudo: false
dist: xenial
python:
 - "3.6"
 - "3.7"
env:
 - "DJANGO_VERSION=1.11.26"
 - "DJANGO_VERSION=2.0.13"
 - "DJANGO_VERSION=2.1.14"
 - "DJANGO_VERSION=2.2.7"
install:
 - "pip install Django==$DJANGO_VERSION"
 - "python setup.py install"
script: "python tests/runtests.py"
